<a href="https://colab.research.google.com/github/vivekalex61/machine-learning/blob/master/neural.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X=np.array([[0,0],[1,0],[1,1],[0,1]])
y=np.array([[0,1,1,1]])
y=y.reshape(4,1)

(4, 2)

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

def sg_derv(x):
  return sigmoid(x)*(1-sigmoid(x))


In [ ]:
weights=np.array([[.2],[.3]])
bias=.3
lr=.05
for i in range(15000):
  inputs=X
  z=np.dot(inputs,weights)+bias
  sig_z=sigmoid(z)
  error=sig_z-y
  
  de_do=error
  do_dz=sigmoid_der(sig_z)
  de_dz=de_do*do_dz
  
  inputs=X.T
  final_der=np.dot(inputs,de_dz)
  
  weights=weights-lr*final_der
  for i in de_dz:
    bias=bias-lr*i
  

In [ ]:
print(weights)
print(bias)


[[7.84285416]
 [7.84299515]]
[-3.57196249]


In [ ]:
#predicting the input 1,1
p=np.array([1,1])
s=(np.dot(p,weights) )+ bias
sigmoid(s)


array([0.99998109])

[[7.00922425]
 [7.00953281]]
